name: Environment variable

on:
    push:
        branches:
            - main
env:
    LIKE: Please, like, share  
    SUBSCRIBE: Subscribe to my youtube channel


jobs:
  My-channel:
    runs-on: ubuntu-latest
    steps: 
    - name: "Please like, share and subscribe to my youtube channel"
      run: echo "$LIKE and $SUBSCRIBE"